[metadata]
addr = 0x435b30
size = 0xf3b
last_change = 2023-07-24T06:23:46.228022Z

[header]
last_change = 2023-07-24T06:23:46.228022Z
name = "sub_435b30"
addr = 0x435b30
type = "ulong"

[header.args.0]
offset = 0x0
name = "arg1"
type = "int128_t*"
size = 0x8

[header.args.1]
offset = 0x1
name = "arg2"
type = "char (*"
size = 0x8

[header.args.2]
offset = 0x2
name = "arg3"
type = "long"
size = 0x8

[header.args.3]
offset = 0x3
name = "arg4"
type = "long"
size = 0x8

[header.args.4]
offset = 0x4
name = "arg5"
type = "int"
size = 0x4

[header.args.5]
offset = 0x5
name = "arg6"
type = "long"
size = 0x8

[header.args.6]
offset = 0x6
name = "arg7"
type = "long"
size = 0x8

[header.args.7]
offset = 0x7
name = "arg8"
type = "char"
size = 0x10

[header.args.8]
offset = 0x8
name = "arg9"
type = "char"
size = 0x10

[header.args.9]
offset = 0x9
name = "arg10"
type = "char"
size = 0x10

[header.args.16]
offset = 0xa
name = "arg11"
type = "char"
size = 0x10

[header.args.17]
offset = 0xb
name = "arg12"
type = "int128_t"
size = 0x10
